litrevu/authentication/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from .views import SignupView, redirection, CustomLoginView

app_name = 'authentication'

urlpatterns = [
    path('', redirection, name='redirect'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(
        next_page='authentication:login'),
        name='logout'),
    path('signup/', SignupView.as_view(), name='signup'),
]

litrevu/litrevu/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls', 'authentication')),
    path('reviews/', include('reviews.urls', 'reviews')),
    path('', lambda request: redirect('authentication:redirect')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

litrevu/authentication/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    """ Custom User Model """
    profile_picture = models.ImageField(
        upload_to="avatars/",
        null=True,
        blank=True
    )

litrevu/authentication/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from .models import User


class SignupForm(UserCreationForm):
    """Custom form for creating new users"""

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({
            'placeholder': 'Nom d\'utilisateur'
        })
        self.fields['password1'].widget.attrs.update({
            'placeholder': 'Mot de passe'
        })
        self.fields['password2'].widget.attrs.update({
            'placeholder': 'Confirmer le mot de passe'
        })

class LoginForm(AuthenticationForm):
    """Custom form for logging in"""

    class Meta:
        model = User
        fields = ['username', 'password']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({
            'placeholder': 'Nom d\'utilisateur'
        })
        self.fields['password'].widget.attrs.update({
            'placeholder': 'Mot de passe'
        })

litrevu/authentication/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_not_required
from django.contrib.auth import login
from django.contrib.auth.views import LoginView
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator

from django.views.generic import CreateView

from .forms import SignupForm, LoginForm
from .models import User


def redirection(request):
    """ function view to redirect to if connected => feed else login """
    if request.user.is_authenticated:
        return redirect('reviews:feed')
    return redirect("authentication:login")


class RedirectAuthenticatedUserMixin:
    """Redirects users who are already logged in"""
    redirect_url = '/reviews/'

    def dispatch(self, request, *args, **kwargs):
        """Verify user is logged in and redirect"""
        if request.user.is_authenticated:
            messages.add_message(request, messages.INFO, self.message_redirection)
            return redirect(self.redirect_url)
        return super().dispatch(request, *args, **kwargs)


@method_decorator(login_not_required, name='dispatch')
class CustomLoginView(RedirectAuthenticatedUserMixin, LoginView):
    """ Custom Login View """
    template_name = "authentication/login.html"
    redirect_authenticated_user = True
    form_class = LoginForm
    message_redirection = "Vous êtes déjà connecté(e)."

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request,
                         f"Bienvenue {self.request.user.username}")
        return response


@method_decorator(login_not_required, name='dispatch')
class SignupView(RedirectAuthenticatedUserMixin, CreateView):
    """ Custom Signup View """
    model = User
    form_class = SignupForm
    template_name = 'authentication/signup.html'
    message_redirection = "Vous ne pouvez pas créer un nouveau utilisateur."
    success_url = reverse_lazy('reviews:feed')

    def form_valid(self, form):
        response = super().form_valid(form)
        login(self.request, self.object)
        messages.success(self.request, 'Compte créé avec succès!')
        return response

litrevu/authentication/templates/authentication/login.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'authentication/css/login.css' %}">
{% endblock %}

{% block title %}Connexion - LITRevu{% endblock %}

{% block content %}
<div class="container">
    <div class="login-form">

        <div class="login-header">
            <h2>LITRevu</h2>
            <p>Connectez-vous</p>
        </div>

        <form method="post">
            {% csrf_token %}
            <div>
                <label for="{{ form.username.id_for_label }}">Nom d'utilisateur</label>
                {{ form.username }}
            </div>
            <div>
                <label for="{{ form.password.id_for_label }}">Mot de passe</label>
                {{ form.password }}
            </div>
            <button type="submit" >Se connecter</button>
        </form>

        {% if form.non_field_errors %}
            <div class="error">
                {% for field in form.non_field_errors %}
                    {% if field != '__all__'%}
                        <p>{{field}}</p>
                    {% endif %}
                {% endfor %}
            </div>
        {% endif %}

        <div class="signup-link">
            <p>Pas encore de compte ?  <a href="{% url 'authentication:signup' %}">S'inscrire</a></p>
        </div>

    </div>
</div>
{% endblock %}

litrevu/authentication/templates/authentication/signup.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'authentication/css/signup.css' %}">
{% endblock %}

{% block title %}Inscription - LITRevu{% endblock %}

{% block content %}
<div class="container">
    <div class="signup-form">
        <div class="signup-header">
            <h2>LITRevu</h2>
            <p>Inscrivez-vous maintenant</p>
        </div>

        <form method="post">
            {% csrf_token %}

            <div class="form-group">
                <label for="{{ form.username.id_for_label }}">Nom d'utilisateur</label>
                {{ form.username }}
                {% if form.username.errors %}
                    <div class="error">{{ form.username.errors }}</div>
                {% endif %}
            </div>

            <div class="form-group">
                <label for="{{ form.password1.id_for_label }}">Mot de passe</label>
                {{ form.password1 }}
                {% if form.password1.errors %}
                    <div class="error">{{ form.password1.errors }}</div>
                {% endif %}
            </div>

            <div class="form-group">
                <label for="{{ form.password2.id_for_label }}">Confirmer le mot de passe</label>
                {{ form.password2 }}
                {% if form.password2.errors %}
                    <div class="error">{{ form.password2.errors }}</div>
                {% endif %}
            </div>

            <button type="submit">S'inscrire</button>
        </form>

        <div class="login-link">
            <p>Déjà un compte ? <a href="{% url 'authentication:login' %}">Se connecter</a></p>
        </div>
    </div>
</div>
{% endblock %}