litrevu/authentication/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from .views import SignupView, redirection, CustomLoginView

app_name = 'authentication'

urlpatterns = [
    path('', redirection, name='redirect'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(
        next_page='authentication:login'),
        name='logout'),
    path('signup/', SignupView.as_view(), name='signup'),
]

litrevu/litrevu/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls', 'authentication')),
    path('reviews/', include('reviews.urls', 'reviews')),
    path('', lambda request: redirect('authentication:redirect')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

litrevu/reviews/urls.py
from django.urls import path
from .views import (
    FeedView,
    PostView,
    FollowView,
    follow_user,
    unfollow_user,
    blocked_user,
    unblocked_user,
    search_user,
    TicketCreateView,
    TicketUpdateView,
    TicketDeleteView,
    ReviewCreateView,
    ReviewUpdateView,
    ReviewDeleteView
)

app_name = 'reviews'

urlpatterns = [
    path("", FeedView.as_view(), name='feed'),
    path("posts/", PostView.as_view(), name='posts'),

    # url for views follow
    path("follow/", FollowView.as_view(), name='follow'),
    path('follow_user/', follow_user, name='follow_user'),
    path('unfollow/<int:user_id>/', unfollow_user, name='unfollow_user'),
    path('blocked/<int:user_id>/', blocked_user, name='blocked_user'),
    path('unblocked/<int:user_id>/', unblocked_user, name='unblocked_user'),
    path("search_user/", search_user, name="search_user"),
    # url for views ticket
    path("tickets/create/", TicketCreateView.as_view(), name="ticket_create"),
    path("tickets/<int:pk>/modify/", TicketUpdateView.as_view(),
         name="ticket_modify"),
    path("tickets/<int:pk>/delete/", TicketDeleteView.as_view(),
         name="ticket_delete"),
    # url for views review
    path("review/create/", ReviewCreateView.as_view(), name="review_create"),
    path("review/create/<int:ticket_id>/", ReviewCreateView.as_view(),
         name="review_create_for_ticket"),
    path("review/<int:pk>/modify/", ReviewUpdateView.as_view(),
         name="review_modify"),
    path("review/<int:pk>/delete/", ReviewDeleteView.as_view(),
         name="review_delete"),
]

litrevu/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}LITRevu{% endblock %}</title>
    <link href="https://fonts.cdnfonts.com/css/satoshi" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block extra_css %}{% endblock %}
</head>
<body >

    <nav>
        <div class="menu">
            <a href="{% url 'reviews:feed' %}" class="logo"><h1>LITRevu</h1></a>
            {% if user.is_authenticated %}
            <div class="nav-links">
                <a href="{% url 'reviews:feed' %}">Flux</a>
                <a href="{% url 'reviews:posts' %}">Posts</a>
                <a href="{% url 'reviews:follow' %}">Abonnements</a>

                <form action="{% url 'authentication:logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit">Déconnexion</button>
                </form>
            </div>
            {% endif %}
        </div>
    </nav>
    {% if messages %}
      {% for message in messages %}
        <div class="banner-message">{{ message }}</div>
      {% endfor %}
    {% endif %}
    <main>
        {% block content %}{% endblock %}
    </main>
</body>
</html>